### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by mkrvanton** [mvisonneau/gitlab-ci-pipelines-exporter#162]
First of all, @mvisonneau thank you so much for that project, the new version works faster and better from my experience, great job!!! 👍 
But for some reason, I got that error all the time when I run docker-compose (after 20-60 min)
Maybe you saw something like that and can help me to solve that issue?

```
{"log":"time=\"2020-10-22T10:12:25Z\" level=debug msg=\"processing job metrics\" job-id=6540633 job-name=ats7_tests project-id=14\n","stream":"stdout","time":"2020-10-22T10:12:25.883685885Z"}
{"log":"time=\"2020-10-22T10:12:25Z\" level=debug msg=\"throttled GitLab requests\" for=564.200953ms\n","stream":"stdout","time":"2020-10-22T10:12:25.884143876Z"}
{"log":"time=\"2020-10-22T10:12:25Z\" level=debug msg=\"processing job metrics\" job-id=6542337 job-name=brt_approvals_tests project-id=14\n","stream":"stdout","time":"2020-10-22T10:12:25.885702562Z"}
{"log":"time=\"2020-10-22T10:12:25Z\" level=debug msg=\"processing job metrics\" job-id=6542254 job-name=xx_base_tests project-id=14\n","stream":"stdout","time":"2020-10-22T10:12:25.886234279Z"}
{"log":"time=\"2020-10-22T10:12:25Z\" level=debug msg=\"processing job metrics\" job-id=6541979 job-name=builder_tests project-id=14\n","stream":"stdout","time":"2020-10-22T10:12:25.886908809Z"}
{"log":"time=\"2020-10-22T10:12:25Z\" level=debug msg=\"processing job metrics\" job-id=6540634 job-name=ats8_tests project-id=14\n","stream":"stdout","time":"2020-10-22T10:12:25.887481552Z"}
{"log":"time=\"2020-10-22T10:12:25Z\" level=debug msg=\"processing job metrics\" job-id=6540635 job-name=ats9_tests project-id=14\n","stream":"stdout","time":"2020-10-22T10:12:25.887900878Z"}
{"log":"time=\"2020-10-22T10:12:25Z\" level=debug msg=\"processing job metrics\" job-id=6540643 job-name=early_adoption_tests project-id=14\n","stream":"stdout","time":"2020-10-22T10:12:25.888203382Z"}
{"log":"time=\"2020-10-22T10:12:25Z\" level=debug msg=\"processing job metrics\" job-id=6540644 job-name=xx_base_tests project-id=14\n","stream":"stdout","time":"2020-10-22T10:12:25.888512602Z"}
{"log":"fatal error: concurrent map read and map write\n","stream":"stderr","time":"2020-10-22T10:12:25.888717716Z"}
{"log":"\n","stream":"stderr","time":"2020-10-22T10:12:25.891945988Z"}
{"log":"goroutine 48078 [running]:\n","stream":"stderr","time":"2020-10-22T10:12:25.892034524Z"}
{"log":"runtime.throw(0xd00f57, 0x21)\n","stream":"stderr","time":"2020-10-22T10:12:25.892230573Z"}
{"log":"\u0009/usr/local/go/src/runtime/panic.go:1112 +0x72 fp=0xc000295a10 sp=0xc0002959e0 pc=0x436052\n","stream":"stderr","time":"2020-10-22T10:12:25.892587632Z"}
{"log":"runtime.mapaccess1_faststr(0xbdef00, 0xc0001ab950, 0xc0013cd430, 0x9, 0x9)\n","stream":"stderr","time":"2020-10-22T10:12:25.892849028Z"}
{"log":"\u0009/usr/local/go/src/runtime/map_faststr.go:21 +0x43c fp=0xc000295a80 sp=0xc000295a10 pc=0x41454c\n","stream":"stderr","time":"2020-10-22T10:12:25.893185357Z"}
{"log":"github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/storage.(*Local).GetMetric(0xc0001fa2a0, 0xc000c9cc20, 0xc0001fa2a0, 0x4)\n","stream":"stderr","time":"2020-10-22T10:12:25.893423436Z"}
{"log":"\u0009/mnt/c/Users/nwrqd3/gitlab.4.0.1/pkg/storage/local.go:141 +0xe4 fp=0xc000295ac0 sp=0xc000295a80 pc=0xa91bc4\n","stream":"stderr","time":"2020-10-22T10:12:25.893739192Z"}
{"log":"github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.storeGetMetric(0xc000c9cc20)\n","stream":"stderr","time":"2020-10-22T10:12:25.89384037Z"}
{"log":"\u0009/mnt/c/Users/nwrqd3/gitlab.4.0.1/pkg/exporter/store.go:220 +0x57 fp=0xc000295db8 sp=0xc000295ac0 pc=0xac7837\n","stream":"stderr","time":"2020-10-22T10:12:25.894156612Z"}
{"log":"github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.processJobMetrics(0xc0001bd250, 0xc00002bae2, 0xc00002bae8, 0xc00002bb0a, 0xc00002bb10, 0xc00002bb41, 0x0, 0x0, 0x0, 0xc000027740, ...)\n","stream":"stderr","time":"2020-10-22T10:12:25.894730084Z"}
{"log":"\u0009/mnt/c/Users/nwrqd3/gitlab.4.0.1/pkg/exporter/jobs.go:115 +0xc56 fp=0xc000296760 sp=0xc000295db8 pc=0xabcd36\n","stream":"stderr","time":"2020-10-22T10:12:25.895064683Z"}
{"log":"github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.pullProjectRefPipelineJobsMetrics(0xc0001bd250, 0xc00002bae2, 0xc00002bae8, 0xc00002bb0a, 0xc00002bb10, 0xc00002bb41, 0x0, 0x0, 0x0, 0xc000027740, ...)\n","stream":"stderr","time":"2020-10-22T10:12:25.895642744Z"}
{"log":"\u0009/mnt/c/Users/nwrqd3/gitlab.4.0.1/pkg/exporter/jobs.go:24 +0x229 fp=0xc000296c08 sp=0xc000296760 pc=0xabbdc9\n","stream":"stderr","time":"2020-10-22T10:12:25.895929776Z"}
{"log":"github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.pullProjectRefMetrics(0xc0001bd250, 0xc00002bae2, 0xc00002bae8, 0xc00002bb0a, 0xc00002bb10, 0xc00002bb41, 0x0, 0x0, 0x0, 0xc000027740, ...)\n","stream":"stderr","time":"2020-10-22T10:12:25.896543923Z"}
{"log":"\u0009/mnt/c/Users/nwrqd3/gitlab.4.0.1/pkg/exporter/pipelines.go:120 +0x133d fp=0xc000297778 sp=0xc000296c08 pc=0xac01fd\n","stream":"stderr","time":"2020-10-22T10:12:25.896893023Z"}
{"log":"github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.glob..func4(0xc0001bd250, 0xc00002bae2, 0xc00002bae8, 0xc00002bb0a, 0xc00002bb10, 0xc00002bb41, 0x0, 0x0, 0x0, 0xc000027740, ...)\n","stream":"stderr","time":"2020-10-22T10:12:25.897459005Z"}

```

**Comment by mvisonneau** [comment]
Thanks for the feedback and the info regarding the issue @mkrvanton 🙇 

I pushed a change in order to fix this issue 49fab27

**Comment by mvisonneau** [comment]
I released it as part of [0.4.2](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/0.4.2), feel free to reopen if you are still seeing the error!

**Comment by mkrvanton** [comment]
Hi @mvisonneau, thanks for the new version!
But I faced the same issue after 28h app running... (previously I got the same error after 20-60 min)
what can be a reason for that error?

```{"log":"time=\"2020-10-24T13:22:21Z\" level=info msg=\"found all jobs to refresh\" jobs-count=32 project-id=14 project-ref=pi_PS-22_Upgrade-PD4ML
{"log":"time=\"2020-10-24T13:22:24Z\" level=info msg=\"found all jobs to refresh\" jobs-count=110 project-id=14 project-ref=pi_PS-21_Enumeration_custom_field_editor
{"log":"time=\"2020-10-24T13:22:24Z\" level=info msg=\"found all jobs to refresh\" jobs-count=0 project-id=14 project-ref=13-fosscheck
{"log":"time=\"2020-10-24T13:22:26Z\" level=info msg=\"found all jobs to refresh\" jobs-count=0 project-id=14 project-ref=2R
{"log":"time=\"2020-10-24T13:22:26Z\" level=info msg=\"found pipeline jobs\" jobs-count=102 pipeline-id=552209 project-id=14 project-ref=1R
{"log":"time=\"2020-10-24T13:22:27Z\" level=info msg=\"found all jobs to refresh\" jobs-count=8 project-id=14 project-ref=wi_PS-21_Live_link
{"log":"time=\"2020-10-24T13:22:27Z\" level=info msg=\"found pipeline jobs\" jobs-count=75 pipeline-id=194237 project-id=14 project-ref=2
{"log":"time=\"2020-10-24T13:22:28Z\" level=info msg=\"found pipeline jobs\" jobs-count=90 pipeline-id=245903 project-id=14 project-ref=3-fosscheck-issue
{"log":"time=\"2020-10-24T13:22:29Z\" level=info msg=\"found all jobs to refresh\" jobs-count=0 project-id=14 project-ref=18.1
{"log":"time=\"2020-10-24T13:22:30Z\" level=info msg=\"found all jobs to refresh\" jobs-count=6 project-id=14 project-ref=wi_PS-214_LDAP_sync
{"log":"time=\"2020-10-24T13:22:30Z\" level=info msg=\"found pipeline jobs\" jobs-count=122 pipeline-id=1080971 project-id=14 project-ref=pi_PS-15_Custom-Field
{"log":"time=\"2020-10-24T13:22:30Z\" level=info msg=\"found all jobs to refresh\" jobs-count=110 project-id=14 project-ref=pi_PS-15_Custom-Field
{"log":"fatal error: concurrent map read and map write
{"log":"
{"log":"goroutine 6539744 [running]:
{"log":"runtime.throw(0xd3f281, 0x21)
{"log":"\u0009/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00204dd78 sp=0xc00204dd48 pc=0x4392d2
{"log":"runtime.mapaccess2(0xc05980, 0xc0001676b0, 0xc00204e868, 0x0, 0xc00204e358)
{"log":"\u0009/usr/local/go/src/runtime/map.go:469 +0x25b fp=0xc00204ddb8 sp=0xc00204dd78 pc=0x41133b
{"log":"github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.processJobMetrics(0xc00002b9c0, 0xc000028f72, 0xc000028f78, 0xc000028f92, 0xc000028f98, 0xc000028fc1, 0x0, 0x0, 0x0, 0xc000024b40, ...)
2020-10-24T13:22:30.39196099Z"}
{"log":"\u0009/pkg/exporter/jobs.go:76 +0x9c8 fp=0xc00204e760 sp=0xc00204ddb8 pc=0xb09328
{"log":"github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.pullProjectRefPipelineJobsMetrics(0xc00002b9c0, 0xc000028f72, 0xc000028f78, 0xc000028f92, 0xc000028f98, 0xc000028fc1, 0x0, 0x0, 0x0, 0xc000024b40, ...)
{"log":"\/pkg/exporter/jobs.go:24 +0x23d fp=0xc00204ec08 sp=0xc00204e760 pc=0xb0861d
{"log":"github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.pullProjectRefMetrics(0xc00002b9c0, 0xc000028f72, 0xc000028f78, 0xc000028f92, 0xc000028f98, 0xc000028fc1, 0x0, 0x0, 0x0, 0xc000024b40, ...)
{"log":"\u0009/pkg/exporter/pipelines.go:116 +0x13dc fp=0xc00204f778 sp=0xc00204ec08 pc=0xb0cb3c
{"log":"github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.glob..func4(0xc00002b9c0, 0xc000028f72, 0xc000028f78, 0xc000028f92, 0xc000028f98, 0xc000028fc1, 0x0, 0x0, 0x0, 0xc000024b40, ...)
{"log":"\u0009/pkg/exporter/scheduler.go:50 +0x58 fp=0xc00204f9c0 sp=0xc00204f778 pc=0xb175f8```

**Comment by mvisonneau** [comment]
argh, sorry about that! It looks like another area of the codebase this time, I'll have a look into it

**Comment by mkrvanton** [comment]
> argh, sorry about that! It looks like another area of the codebase this time, I'll have a look into it

@mvisonneau thank you a lot! :)

**Comment by mvisonneau** [comment]
Alright so I did not manage to point the finger upon this exact issue but I sorted out the tests to be able to reenable the `-race` flag (#157) it could be related to this issue but I am not fully sure!

**Comment by mvisonneau** [comment]
@mkrvanton I added further changes which I believe will help with this issue as part of the [v0.4.3](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/v0.4.3) release, feel free to upgrade and reopen if necessary!

**Comment by mkrvanton** [comment]
> @mkrvanton I added further changes which I believe will help with this issue as part of the [v0.4.3](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/v0.4.3) release, feel free to upgrade and reopen if necessary!

@mvisonneau  Thank you so much! :)
