### ISSUE TITLE
Exporter dying (memory related)

### ISSUE THREAD

**Issue by vakaobr** [mvisonneau/gitlab-ci-pipelines-exporter#17]
Hello there,

First: Thanks for you code!

I'm getting a error while trying to deploy it using multiple projects (with 4 projects that work normally):

```
time="2019-09-06T20:29:51Z" level=info msg="Polling myproject-saas/ci-cd-test:dev (1039)"
time="2019-09-06T20:29:51Z" level=warning msg="Could not find any pipeline for myproject-saas/ci-cd-test:master"
time="2019-09-06T20:29:51Z" level=warning msg="Could not find any pipeline for myproject-saas/ci-cd-test:integ"
time="2019-09-06T20:29:51Z" level=warning msg="Could not find any pipeline for myproject-saas/ci-cd-test:dev"
time="2019-09-06T20:29:51Z" level=info msg="Found ref 'master' for project 'myproject-saas/back-end/complexity-api'"
time="2019-09-06T20:29:51Z" level=info msg="Polling myproject-saas/back-end/complexity-api:master (2617)"
time="2019-09-06T20:29:51Z" level=info msg="Found ref 'master' for project 'myproject-saas/nginx-mock-data'"
time="2019-09-06T20:29:51Z" level=info msg="Polling myproject-saas/nginx-mock-data:master (470)"
time="2019-09-06T20:29:51Z" level=info msg="Found ref 'master' for project 'myproject-saas/back-end/user-count-api'"
time="2019-09-06T20:29:51Z" level=info msg="Polling myproject-saas/back-end/user-count-api:master (1332)"
time="2019-09-06T20:29:51Z" level=info msg="Found ref 'master' for project 'myproject-saas/back-end/flow-api'"
time="2019-09-06T20:29:51Z" level=info msg="Polling myproject-saas/back-end/flow-api:master (1376)"
time="2019-09-06T20:29:51Z" level=info msg="Found ref 'master' for project 'myproject-saas/back-end/capa-plans-api'"
time="2019-09-06T20:29:51Z" level=info msg="Polling myproject-saas/back-end/capa-plans-api:master (1213)"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x89f951]

goroutine 212 [running]:
main.(*client).pollProjectRef(0xc000108d30, 0xc00011ab40, 0xc0004113e8, 0x6)
	/build/exporter.go:350 +0x681
created by main.(*client).pollProject
	/build/exporter.go:310 +0x1e5
```

**Comment by mvisonneau** [comment]
👋 thanks for raising the issue @vakaobr! It should be fixed with https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/76423c93061b9f770eeebe7ad53f2ba7c27e70a7

**Comment by vakaobr** [comment]
Hello there,

Sorry by comment in a closed issue.

Today I did a change on my configuration, and set my `default_refs:` to `"^.*"`

That is supported by your code ? I also updated to 0.2.7 version and started to get memory dying errors again:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x89f951]
 goroutine 263 [running]:
main.(*client).pollProjectRef(0xc000065cf0, 0xc00022e000, 0xc0002be038, 0x5)
	/build/exporter.go:350 +0x681
created by main.(*client).pollProject
	/build/exporter.go:310 +0x1e5
```

**Comment by mvisonneau** [comment]
This is odd given that the `/exporter.go` file doesn't exist since **0.2.6**. Are you sure this is using the latest version ? 🤔

The regex seems to be valid, in doubt you can check it here https://regex101.com/
