### ISSUE TITLE
Panic on DNS lookup failure

### ISSUE THREAD

**Issue by mvisonneau** [mvisonneau/gitlab-ci-pipelines-exporter#21]
Recently experienced the following issue when a DNS lookup failed

```
{"level":"error","msg":"ListProjectPipelines: Get https://git.example.com/api/v4/projects/72/pipelines?ref=master: dial tcp: lookup git.sph.re on 10.4.64.10:53: read udp 10.5.1.25:56257-\u003e10.4.64.10:53: read: connection refused","time":"2019-10-01T14:29:54Z"}
panic: runtime error: index out of range [0] with length 0

goroutine 2555 [running]:
github.com/mvisonneau/gitlab-ci-pipelines-exporter/cmd.(*Client).pollProjectRef(0xc0000e03e8, 0xc000582900, 0xc0003a2096, 0x6)
	/build/cmd/gitlab.go:275 +0xf30
created by github.com/mvisonneau/gitlab-ci-pipelines-exporter/cmd.(*Client).pollProject
	/build/cmd/gitlab.go:244 +0x595
```

Need to implement correct handling of this error.

exporter version : `0.2.8`

**Comment by mvisonneau** [comment]
should be fixed by #26 , thanks @agilob !
