### ISSUE TITLE
Polling error

### ISSUE THREAD

**Issue by mvisonneau** [mvisonneau/gitlab-ci-pipelines-exporter#3]
I got an error, I can not understand what it is

2019/02/12 06:48:56 -> Starting exporter
2019/02/12 06:48:56 -> Polling *** every 30s
2019/02/12 06:48:56 -> 10 project(s) configured
2019/02/12 06:48:56 --> Polling ID: 286 | ***
...
2019/02/12 06:48:56 --> Polling ID: 261 | ***
panic: runtime error: index out of range

goroutine 16 [running]:
main.main.func1(0xc42009b200, 0xc4200165c0, 0xc420012e60, 0x11, 0xc420014cc0, 0x6)
	/go/src/github.com/mvisonneau/gitlab-ci-pipelines-exporter/main.go:127 +0xafb
created by main.main
	/go/src/github.com/mvisonneau/gitlab-ci-pipelines-exporter/main.go:108 +0x316

_Originally posted by @Sakojpa in https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/1#issuecomment-462640716_

**Comment by mvisonneau** [comment]
should be fixed in `v0.2.0`, let's reopen otherwise
