### ISSUE TITLE
Exporter dying (memory related)

### ISSUE THREAD

**Issue by OPSTime** [mvisonneau/gitlab-ci-pipelines-exporter#314]
**I'm getting a error while trying to deploy it using multiple projects (52 projects):**

```
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xadc4a4]
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: goroutine 13 [running]:
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/gitlab.(*Client).rateLimit(...)
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/gitlab/client.go:96
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/gitlab.(*Client).GetProject(0x0, 0xc0001fa440, 0x11, 0x0, 0x0, 0x0)
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/gitlab/projects.go:19 +0x184
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.pullRefsFromProject(0xc0001f65ec, 0x0, 0x0, 0xc00028a900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter/refs.go:60 +0xbb
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.glob..func4(0xc0001f65ec, 0x0, 0x0, 0xc00028a900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter/scheduler.go:52 +0x65
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: reflect.Value.call(0xbeedc0, 0xd71f50, 0x13, 0xd3dc70, 0x4, 0xc00000dc80, 0x1, 0x1, 0xc000067da8, 0x477945, ...)
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: reflect/value.go:476 +0x8c7
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: reflect.Value.Call(0xbeedc0, 0xd71f50, 0x13, 0xc00000dc80, 0x1, 0x1, 0x0, 0xc000067de8, 0xc000067df8)
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: reflect/value.go:337 +0xb9
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/vmihailenco/taskq/v3.(*reflectFunc).HandleMessage(0xc00019e420, 0xc000194f70, 0xd4d052, 0x17)
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/vmihailenco/taskq/v3@v3.2.3/handler.go:78 +0x8d
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/vmihailenco/taskq/v3.(*Task).HandleMessage(0xc00019e450, 0xc000194f70, 0x17, 0xc00019e450)
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/vmihailenco/taskq/v3@v3.2.3/task.go:112 +0xa2
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/vmihailenco/taskq/v3.(*TaskMap).HandleMessage(0x129f6c0, 0xc000194f70, 0x0, 0x0)
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/vmihailenco/taskq/v3@v3.2.3/registry.go:71 +0xb3
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/vmihailenco/taskq/v3.(*Consumer).Process(0xc0001a8540, 0xc000194f70, 0xc000020438, 0xc000224780)
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/vmihailenco/taskq/v3@v3.2.3/consumer.go:538 +0x14d
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/vmihailenco/taskq/v3.(*Consumer).worker(0xc0001a8540, 0xe23be0, 0xc000020438, 0x0)
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/vmihailenco/taskq/v3@v3.2.3/consumer.go:479 +0x176
Aug 17 20:07:20 ip-xxxx systemd[1]: gitlab-ci-pipelines-exporter.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/vmihailenco/taskq/v3.(*Consumer).addWorker.func1(0xc0001a8540, 0xe23be0, 0xc000020438, 0xc000000000)
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/vmihailenco/taskq/v3@v3.2.3/consumer.go:275 +0x74
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: created by github.com/vmihailenco/taskq/v3.(*Consumer).addWorker
Aug 17 20:07:20 ip-xxxx gitlab-ci-pipelines-exporter[29221]: github.com/vmihailenco/taskq/v3@v3.2.3/consumer.go:273 +0xd3
Aug 17 20:07:20 ip-xxxx systemd[1]: Unit gitlab-ci-pipelines-exporter.service entered failed state.
Aug 17 20:07:20 ip-xxxx systemd[1]: gitlab-ci-pipelines-exporter.service failed.
Aug 17 20:07:23 ip-xxxx systemd[1]: gitlab-ci-pipelines-exporter.service holdoff time over, scheduling restart.
Aug 17 20:07:23 ip-xxxx systemd[1]: Stopped gitlab-ci-pipelines-exporter.
```

**cat gitlab-ci-pipelines-exporter.yml**
```
log:
  level: debug

  format: text

server:
  listen_address: 0.0.0.0:8080
  enable_pprof: false
  metrics:
    enabled: true

gitlab:
  url: https://gitlab.example.com
  token: xxxx

pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false
  environments_from_projects:
    on_init: false
    scheduled: false
  refs_from_projects:
    on_init: true
    scheduled: true
    interval_seconds: 900
  metrics:
    on_init: true
    scheduled: true
    interval_seconds: 300

# Pull jobs related metrics on all projects
project_defaults:
  pull:
    pipeline:
      jobs:
        enabled: true

projects:
  - name: wisers-front-end/next-datacenter
    pull:
      environments:
        enabled: true
      refs:
        regexp: ".*"

......

```

**Comment by mvisonneau** [comment]
Indeed, thanks for raising this issue @OPSTime, it should be fixed with  8197476
