### ISSUE TITLE
gitlab_ci_pipelines_exporter monitor caught panic

### ISSUE THREAD

**Issue by scor2k** [mvisonneau/gitlab-ci-pipelines-exporter#334]
After 5-6 minutes exporter is running monitor stop working. 

```
Caught panic:

strings: negative Repeat count

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).Start.func2()
	github.com/charmbracelet/bubbletea@v0.14.1/tea.go:447 +0x95
panic({0xd57700, 0x10b1e40})
	runtime/panic.go:1038 +0x215
strings.Repeat({0xc000024ae0, 0x3}, 0xc000385cd0)
	strings/strings.go:529 +0x4d8
github.com/charmbracelet/bubbles/progress.Model.bar({0xd3, 0x2588, {0xed0c6c, 0x7}, 0x2591, {0xed0bee, 0x7}, 0x1, {0xed6c51, 0x8}, ...}, ...)
	github.com/charmbracelet/bubbles@v0.8.0/progress/progress.go:173 +0x52e
github.com/charmbracelet/bubbles/progress.Model.View({0xd3, 0x2588, {0xed0c6c, 0x7}, 0x2591, {0xed0bee, 0x7}, 0x1, {0xed6c51, 0x8}, ...}, ...)
	github.com/charmbracelet/bubbles@v0.8.0/progress/progress.go:135 +0x170
github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/monitor/ui.(*model).renderLastStatus(0xc000425988)
	github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/monitor/ui/ui.go:169 +0x2a5
github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/monitor/ui.model.Update({{0x10adcf4, 0x5}, 0xc0000d8360, 0xc000695a30, 0xc000034960, 0xc0000f4700, {0xee, 0x3d, 0x0, 0x0, ...}, ...}, ...)
	github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/monitor/ui/ui.go:273 +0xda
github.com/charmbracelet/bubbletea.(*Program).Start(0xc0000d83f0)
	github.com/charmbracelet/bubbletea@v0.14.1/tea.go:589 +0xc42
github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/monitor/ui.Start({0x10adcf4, 0x0}, 0x0)
	github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/monitor/ui/ui.go:342 +0x5b
github.com/mvisonneau/gitlab-ci-pipelines-exporter/internal/cmd.Monitor(0xc00012ff00)
	github.com/mvisonneau/gitlab-ci-pipelines-exporter/internal/cmd/monitor.go:15 +0x50
github.com/mvisonneau/gitlab-ci-pipelines-exporter/internal/cmd.ExecWrapper.func1(0xc0006959b0)
	github.com/mvisonneau/gitlab-ci-pipelines-exporter/internal/cmd/utils.go:94 +0x1d
github.com/urfave/cli/v2.(*Command).Run(0xc000126120, 0xc00012fe40)
	github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
github.com/urfave/cli/v2.(*App).RunContext(0xc000268d00, {0x10ced48, 0xc000026bb8}, {0xc00001e040, 0x2, 0x2})
	github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.3.0/app.go:224
github.com/mvisonneau/gitlab-ci-pipelines-exporter/internal/cli.Run({0x10adcf4, 0x5}, {0xc00001e040, 0x2, 0x2})
	github.com/mvisonneau/gitlab-ci-pipelines-exporter/internal/cli/cli.go:14 +0x70
main.main()
	github.com/mvisonneau/gitlab-ci-pipelines-exporter/cmd/gitlab-ci-pipelines-exporter/main.go:12 +0x3c
```

**Comment by guiljin** [comment]
once the task queue is overflowed, then the monitor crashed
