### ISSUE TITLE
Nil pointer exporting metrics

### ISSUE THREAD

**Issue by gallipi** [mvisonneau/gitlab-ci-pipelines-exporter#370]
Hi mvisonneau, 

I'm using version 0.47 of the exporter. It was working fine but the number of projects has increased considerably and now the exporter crashes after 2 minutes downloading metrics.

### LOG
**panic: runtime error: invalid memory address or nil pointer dereference**

[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xae469e]

_goroutine 25 [running]:
github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/gitlab.(*Client).GetCommitCountBetweenRefs(0xc0002d3200, 0xc0000163c0, 0x2f, 0x0, 0x0, 0xc0010b5f08, 0x8, 0x41d8634bcec00000, 0x0, 0x0)
        github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/gitlab/repositories.go:23 +0x41e
github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.pullEnvironmentMetrics(0xc0000163c0, 0x2f, 0xb6, 0xc00057ef5b, 0x3, 0xc00041b530, 0x25, 0x1, 0x0, 0xd4b9b5, ...)
        github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter/environments.go:121 +0x7e5
github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter.glob..func3(0xc0000163c0, 0x2f, 0xb6, 0xc00057ef5b, 0x3, 0xc00041b530, 0x25, 0x1, 0x0, 0xd4b9b5, ...)
        github.com/mvisonneau/gitlab-ci-pipelines-exporter/pkg/exporter/scheduler.go:37 +0x58
reflect.Value.call(0xbf7b20, 0xd81dd8, 0x13, 0xd48edf, 0x4, 0xc0005a7260, 0x1, 0x1, 0xc0006f3da8, 0x47774f, ...)
        reflect/value.go:476 +0x8c7
reflect.Value.Call(0xbf7b20, 0xd81dd8, 0x13, 0xc0005a7260, 0x1, 0x1, 0x0, 0xc0006f3de8, 0xc0006f3df8)
        reflect/value.go:337 +0xb9
github.com/vmihailenco/taskq/v3.(*reflectFunc).HandleMessage(0xc0002d2330, 0xc00009cea0, 0xd5f0be, 0x1a)
        github.com/vmihailenco/taskq/v3@v3.2.3/handler.go:78 +0x8d
github.com/vmihailenco/taskq/v3.(*Task).HandleMessage(0xc0002d2360, 0xc00009cea0, 0x1a, 0xc0002d2360)
        github.com/vmihailenco/taskq/v3@v3.2.3/task.go:112 +0xa2
github.com/vmihailenco/taskq/v3.(*TaskMap).HandleMessage(0x12be720, 0xc00009cea0, 0x0, 0x0)
        github.com/vmihailenco/taskq/v3@v3.2.3/registry.go:71 +0xb3
github.com/vmihailenco/taskq/v3.(*Consumer).Process(0xc0002df140, 0xc00009cea0, 0xc000120418, 0xc0000be050)
        github.com/vmihailenco/taskq/v3@v3.2.3/consumer.go:538 +0x14d
github.com/vmihailenco/taskq/v3.(*Consumer).worker(0xc0002df140, 0xe34fc0, 0xc000120418, 0x0)
        github.com/vmihailenco/taskq/v3@v3.2.3/consumer.go:479 +0x176
github.com/vmihailenco/taskq/v3.(*Consumer).addWorker.func1(0xc0002df140, 0xe34fc0, 0xc000120418, 0xc000000000)
        github.com/vmihailenco/taskq/v3@v3.2.3/consumer.go:275 +0x74
created by github.com/vmihailenco/taskq/v3.(*Consumer).addWorker
        github.com/vmihailenco/taskq/v3@v3.2.3/consumer.go:273 +0xd3_

### CONFIG:

_server:
  webhook:
    enabled: true
    secret_token: xxxx

gitlab:
  url: https://xxxxx
  token: xxxxx

pull:
  projects_from_wildcards:
    on_init: true
    interval_seconds: 3000

  environments_from_projects:
    on_init: true
    interval_seconds: 2000

  refs_from_projects:
    on_init: true
    interval_seconds: 800

  metrics:
    on_init: true
    interval_seconds: 500

project_defaults:
  pull:
    environments:
      enabled: true

    refs:
      regexp: "(^master$|^develop$|^feature|^hotfix|^bugfix)"

    pipeline:
      jobs:
        enabled: true
        from_child_pipelines:
          enabled: false
wildcards:

  - owner: { name: xxxx, kind: group }
  - owner: { name: xxxx/yyyy, kind: group, include_subgroups: true }
  - owner: { name: xxxx/yyyy, kind: group, include_subgroups: true }
  - owner: { name: xxxx/yyyy, kind: group, include_subgroups: true }
  - owner: { name: xxxx/yyyy, kind: group, include_subgroups: true }
  - owner: { name: xxxx/yyyy, kind: group, include_subgroups: true }

  - owner: { name: xxxx/yyyy, kind: group, include_subgroups: true }
    search: 'aaaa'
  - owner: { name: xxxx/yyyy, kind: group, include_subgroups: true }
    search: 'bbbb'
  - owner: { name: xxxx/yyyy, kind: group, include_subgroups: true }
    search: 'cccc'
  - owner: { name: xxxx/yyyy, kind: group, include_subgroups: true }
    search: 'dddd'
  - owner: { name: xxxx/yyyy, kind: group, include_subgroups: true }
    search: 'eeee'
  - owner: { name: xxxx/yyyy, kind: group, include_subgroups: true }
    search: 'ffff'
  - owner: { name: xxxx/yyyy, kind: group, include_subgroups: true }
    search: 'hhhh'
  - owner: { name: xxxx/yyyy, kind: group, include_subgroups: true }
    search: 'jjjj'_

Thanks in advance and congratulations for this great job

**Comment by gallipi** [comment]
Solved updating exporter to 0.52
