### ISSUE TITLE
Go Error - panic: runtime error: index out of range

### ISSUE THREAD

**Issue by LaurentDumont** [mvisonneau/gitlab-ci-pipelines-exporter#6]
Hi!

I have a test setup with the following config.yml
```yaml
# URL and Token with sufficient permissions to access your GitLab's projects
# pipelines informations
gitlab:
  url: http://gitlab.cmaker.studio
  token: potato

# Waiting time between polls for each projects
polling_interval_seconds: 30

# The list of the projects you want to monitor
projects:
  - name: root/test1
    ref: master
  - name: root/test2
    ref: master
  - name: root/test3
    ref: master
```

The container starts correctly but it's crashing with the following error
```sh
root@docker01:/opt/gitlab-ci-exporter# docker run -d    --name gitlab-ci-pipelines-exporter    -v $(pwd)/config-test.yml:/etc/config.yml    -p 8080:8080    gitlabci-pipeline-cmaker:latest    -config /etc/config.yml
f82ac2c868cf2f16bc0f50e377d37a27c934b6fc75acae5958a37166b0e13149
root@docker01:/opt/gitlab-ci-exporter# docker logs f82ac2c868cf2f16bc0f50e377d37a27c934b6fc75acae5958a37166b0e13149
2019/07/19 04:38:03 -> Starting exporter
2019/07/19 04:38:03 -> Polling http://gitlab.cmaker.studio every 30s
2019/07/19 04:38:03 -> 3 project(s) configured
2019/07/19 04:38:03 --> Polling ID: 2 | root/test2:master
panic: runtime error: index out of range

goroutine 12 [running]:
main.main.func1(0xc0000a1400, 0xc00005a780, 0xc0000269f0, 0xa, 0xc000026a08, 0x6)
	/build/main.go:126 +0xbe7
created by main.main
	/build/main.go:108 +0x3af
```
If I switch to monitoring a single project. It works correctly and does not crash. 2 or more projects and the container crashes when launched.

I saw on old issue but you mentioned a fix being in the current release.

Any ideas?

**Comment by mvisonneau** [comment]
hmm indeed, it seems to be the same thing as for #3 I'll try to reproduce

**Comment by mvisonneau** [comment]
I managed to reproduce the issue. It seems to be happening whenever there is not a single pipeline created for the `project:ref`. This commit should fix it : https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/2713ebdfa53d676e350ba651cc744a31b5fbbe77#diff-7ddfb3e035b42cd70649cc33393fe32cR174
